name: Build
on: push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/winny/pre-commit-docker:latest
      env:
        PRE_COMMIT_HOME: .pre-commit-cache
    steps:
      - uses: actions/checkout@v4
      - name: Allow workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Cache .pre-commit-cache
        uses: actions/cache@v3
        with:
          path: |
            .pre-commit-cache
          key: ${{ runner.os }}-pre-commit-cache-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: pre-commit run -a
  test:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      # Note that cachix-action isn't used here.  It adds a couple seconds to
      # CI time, so if nothing is cachable, just save those seconds.  You'd
      # waste a minute of CI time for every 15 runs.
      - run: nix build .#super_rogue.test # Separate out the noisy nix output
                                          # from running tests.
      - run: nix run .#super_rogue.test
