name: Release
on:
  workflow_run:
    workflows:
      - Build
    branches:
      - master
    types:
      - completed
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: channel:nixos-22.11
      - run: nix-env -i awscli -f '<nixpkgs>'
      - run: |
          env | grep -o "^AWS_[^=]*"
          echo $AWS_ACCESS_KEY_ID | wc -c
          echo $AWS_SECRET_ACCESS_KEY | wc -c
          src=s3://winny-super-rogue/${GITHUB_SHA}/
          dest=s3://winny-super-rogue/
          aws s3 sync --acl public-read "$src" "$dest"
          echo https://super-rogue.workinprogress.top/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
